### ISSUE TITLE
[FEAT] : add title tab logo to webpage

### ISSUE THREAD

**Issue by GaneshRenuse** [GaneshRenuse/GaneshRenuse-Portfolio#5]
**Is your feature request related to a problem? Please describe.**
When you open the webpage you will see there is no logo in the title bar  its empty and has only title.

**Describe the solution you'd like**
add the company logo to the title tab which look more better when people see your webpage

**Describe alternatives you've considered**
make a simple aesthetic logo of your brand and add it.

**Additional context**
![Screenshot (52)](https://github.com/GaneshRenuse/web-development/assets/92455602/cbd8c6a9-56e1-45df-a2f9-8eed6fc6920f)

**Comment by AbhishekMaurya2002** [comment]
Can you assign to me?

**Comment by GaneshRenuse** [comment]
sure!!  
assigned to you👍
